class PracticePageLocators:
    LINK = "/automation-practice-form"
    FIRST_NAME = '#firstName'
    LAST_NAME = '#lastName'
    EMAIL = '#userEmail'
    GENDER_MALE = '[for=gender-radio-1]'
    GENDER_FEMALE = '[for=gender-radio-2]'
    GENDER_OTHER = '[for=gender-radio-3]'
    PHONE = '#userNumber'
    DATE_OF_BIRTH = '#dateOfBirthInput'
    SUBJECTS = '#subjectsInput'
    HOBBIES_SPORTS = '[for="hobbies-checkbox-1"]'
    HOBBIES_READING = '[for="hobbies-checkbox-2"]'
    HOBBIES_MUSIC = '[for="hobbies-checkbox-3"]'
    UPLOAD_PICTURE = '#uploadPicture'
    ADDRESS_CURRENT = '#currentAddress'
    STATE = '#state'
    CITY = '#city'
    STATE_OPTION_NCR = '//div[contains(text(), "NCR")]'
    STATE_OPTION_UTTAR_PRADESH = '//div[contains(text(), "Uttar Pradesh")]'
    STATE_OPTION_HARYANA = '//div[contains(text(), "Haryana")]'
    STATE_OPTION_RAJASTHAN = '//div[contains(text(), "Rajasthan")]'
    CITY_NCR_GURGAON = '//div[contains(text(), "Gurgaon")]'
    CITY_NCR_DELHI = '//div[contains(text(), "Delhi")]'
    CITY_NCR_NOIDA = '//div[contains(text(), "Noida")]'
    CITY_UTTAR_PRADESH_AGRA = '//div[contains(text(), "Agra")]'
    CITY_UTTAR_PRADESH_LUCKNOW = '//div[contains(text(), "Lucknow")]'
    CITY_UTTAR_PRADESH_MERRUT = '//div[contains(text(), "Merrut")]'
    CITY_HARYANA_KARNAL = '//div[contains(text(), "Karnal")]'
    CITY_HARYANA_PANIPAT = '//div[contains(text(), "Panipat")]'
    CITY_RAJASTHAN_JAIPUR = '//div[contains(text(), "Jaipur")]'
    CITY_RAJASTHAN_JAISELMER = '//div[contains(text(), "Jaiselmer")]'
    SUBMIT_BUTTON = '#submit'
    MODAL_BODY = '.modal-body'

